---
- hosts: 172.31.1.181
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myvariable

  - name: i want to display task1 result
    debug:
      msg: "{{myvariable}}"