---
- hosts: 172.31.1.181
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: copy index.html file into nodes site
    copy:
      src:  myindex.html
      dest: /var/www/html/index.html