---
- hosts: 172.31.1.181
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: copy index.html file into nodes site
    copy:
      src:  myindex.html
      dest: /var/www/html/index.html

  - name: copy myindex.j2 file into nodes site
    template:
      src:  myindex.j2
      dest: /var/www/html/index.html

  - name: i want to download remote files
    get_url:
      url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war 
      dest: /home/ubuntu
      force_basic_auth: yes 