---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install web server on ubuntu
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"  

  - name: i want to start webseever on ubuntu
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family=="Debian"

  - name: i want to install web server on redhat
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"  

  - name: i want to start webseever on redhat
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family=="RedHat"  

  #apt-get install apache2
