---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install web server on ubuntu
    apt:
      name: apache2
      state: present
      

  - name: i want to start webseever on ubuntu
    service:
      name: apache2
      state: started

  #apt-get install apache2
